config/routes.rb
Rails.application.routes.draw do

  root to: 'home#index'

  # Frontend
  resources :document_types, only: [:index, :new, :show]
  resources :documents, only: [:index, :new, :show]

  # API
  namespace :api do
    namespace :v1 do
      resources :document_types do
        resources :questions
      end

      resources :documents do
        resources :answers
      end
    end
  end

end

app/models/answer.rb
class Answer < ApplicationRecord

  # Relations
  belongs_to :document
  belongs_to :question

  # Validations
  validates :body, presence: true

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/document.rb
class Document < ApplicationRecord

  # Relations
  belongs_to :document_type

  has_many :questions, through: :document_type
  has_many :answers, dependent: :destroy

  has_one_attached :file

  accepts_nested_attributes_for :answers, allow_destroy: true, :reject_if => lambda { |a| a[:body].blank? }

  # Validations
  validates :title, presence: true, uniqueness: true
  validate :has_file?
  validate :answered?

  private

  def has_file?
    errors.add(:file, :blank) unless file.attached?
  end

  def answered?
    if document_type
      errors.add(:questions, 'You should answer all questions') \
        unless answers.map(&:question_id) == document_type.questions.map(&:id)
    end
  end

end

app/models/document_type.rb
class DocumentType < ApplicationRecord

  # Relations
  has_many :questions, dependent: :destroy
  has_many :documents, dependent: :destroy
  accepts_nested_attributes_for :questions, allow_destroy: true, :reject_if => lambda { |a| a[:body].blank? }

  # Validations
  validates :title, presence: true, uniqueness: true

end

app/models/question.rb
class Question < ApplicationRecord

  # Relations
  belongs_to :document_type

  # Validations
  validates :body, presence: true

end

app/controllers/api/v1/document_types_controller.rb
class Api::V1::DocumentTypesController < ApplicationController
  before_action :find_document_type, only: [:show, :update, :destroy]

  # GET /document_types
  def index
    @document_types = DocumentType.order(created_at: :desc)

    render json: @document_types
  end

  # GET /document_types/1
  def show
    render json: @document_type
  end

  # POST /document_types
  def create
    @document_type = DocumentType.new(document_type_params)

    if @document_type.save
      render json: @document_type, status: :created
    else
      render json: @document_type.errors, status: :unprocessable_entity
    end
  end

  # PATCH /document_type/1
  def update
    if @document_type.update(document_type_params)
      render json: @document_type
    else
      render json: @document_type.errors, status: :unprocessable_entity
    end
  end

  # DELETE /document_types/1
  def destroy
    if @document_type.destroy
      head :no_content, status: :ok
    else
      render json: @document_type.errors, status: :unprocessable_entity
    end
  end

  private

  def find_document_type
    @document_type = DocumentType.find(params[:id])
  end

  def document_type_params
    params.require(:document_type).permit(:title, questions_attributes: [:id, :body, :_destroy])
  end

end

app/controllers/api/v1/documents_controller.rb
class Api::V1::DocumentsController < ApplicationController
  before_action :find_document, only: [:show, :update, :destroy]

  # GET /documents
  def index
    @documents = Document.order(created_at: :desc)

    render json: @documents
  end

  # GET /documents/1
  def show
    render json: @document
  end

  # POST /documents
  def create
    @document = Document.new(document_params)

    if @document.save
      render json: @document, status: :created
    else
      render json: @document.errors, status: :unprocessable_entity
    end
  end

  # PATCH /document/1
  def update
    if @document.update(document_params)
      render json: @document
    else
      render json: @document.errors, status: :unprocessable_entity
    end
  end

  # DELETE /document/1
  def destroy
    if @document.destroy
      head :no_content, status: :ok
    else
      render json: @document.errors, status: :unprocessable_entity
    end
  end

  private

  def find_document
    @document = Document.find(params[:id])
  end

  def document_params
    params.require(:document).permit(:id, :title, :document_type_id, :file, answers_attributes: [:id, :question_id, :body])
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  skip_before_action :verify_authenticity_token
end

app/controllers/document_types_controller.rb
class DocumentTypesController < ApplicationController

  # GET /document_types
  def index
  end

  # GET /document_types/new
  def new
  end

  # GET /document_types/:id
  def show
  end

end

app/controllers/documents_controller.rb
class DocumentsController < ApplicationController

  # GET /documents
  def index
  end

  # GET /documents/new
  def new
  end

  # GET /documents/:id
  def show
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/document_types/index.html.erb
<%= react_component("DocumentTypes/List") %>

app/views/document_types/new.html.erb
<%= react_component("DocumentTypes/DocumentType") %>

app/views/document_types/show.html.erb
<%= react_component("DocumentTypes/DocumentType", id: params[:id]) %>

app/views/documents/index.html.erb
<%= react_component("Documents/List") %>

app/views/documents/new.html.erb
<%= react_component("Documents/Document") %>

app/views/documents/show.html.erb
<%= react_component("Documents/Document", id: params[:id]) %>

app/views/home/index.html.erb
<div class="jumbotron">
  <h1 class="display-4">Hello, world!</h1>
  <p class="lead">This is a simple document manager. You can define document types with questions. Then while uploading documents, you will have to answer the associated questions</p>
  <hr class="my-4">
  <p>Powered by Ruby on Rails & React JS.</p>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Doc Manager</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application' %>
  </head>

  <body>

    <header>
      <!-- Fixed navbar -->
      <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
        <a class="navbar-brand" href="#">DOC Manager</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarCollapse">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item">
              <a class="nav-link" href="<%= document_types_path %>">Document Types</span></a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="<%= documents_path %>">Documents</a>
            </li>
          </ul>
        </div>
      </nav>
    </header>

    <!-- Begin page content -->
    <main role="main" class="container">
      <%= yield %>
    </main>
  </body>
</html>